config:
  _target_: tace.models.e3nnTACE # [e3nnTACE, eqtTACE, cartTACE] export TACE_USE_OEQ=1 to use openequivariance
  wrapper:
    _target_: tace.models.TensorModel # [TensorModel]

  cutoff: 5.0 # (float), recommend 6.0
  max_neighbors: null # (null, int) if you want to use tace in lammps, do not use max_neighbors
  atomic_numbers: null # (null, list), null = read from dataset.
  fidelity:
    # - {
    #   name: omat24, # (str) custom name
    #   # (null, Dict[int, float])
    #   atomic_energy: {1: -1.11700253, 2: 0.00079886, 3: -0.29731164, 4: -0.04129868, 5: -0.29106192, 6: -1.27751531, 7: -3.12342715, 8: -1.54797136, 9: -0.43969356, 10: -0.01250908, 11: -0.22855413, 12: -0.00943179, 13: -0.21707638, 14: -0.82619133, 15: -1.88667434, 16: -0.89093583, 17: -0.25816211, 18: -0.02414768, 19: -0.17662425, 20: -0.02568319, 21: -2.13001165, 22: -2.38688845, 23: -3.55934233, 24: -5.44700879, 25: -5.14749562, 26: -3.30662847, 27: -1.42167737, 28: -0.63181379, 29: -0.23449167, 30: -0.01146636, 31: -0.21291259, 32: -0.77939897, 33: -1.70148487, 34: -0.78386705, 35: -0.22690657, 36: -0.02245409, 37: -0.16092396, 38: -0.02798717, 39: -2.25685695, 40: -2.23690495, 41: -2.15347771, 42: -4.60251809, 43: -3.36416792, 44: -2.23062607, 45: -1.15550917, 46: -1.47553527, 47: -0.19918102, 48: -0.01475888, 49: -0.19767692, 50: -0.68005773, 51: -1.43073368, 52: -0.65790462, 53: -0.18915279, 54: -0.01179476, 55: -0.13507902, 56: -0.03056979, 57: -0.36017439, 58: -0.86279246, 59: -0.20573327, 60: -0.2734463, 61: -0.20046965, 62: -0.25444338, 63: -8.37972664, 64: -9.58424928, 65: -0.19466184, 66: -0.24860115, 67: -0.19531288, 68: -0.15401392, 69: -0.14577898, 70: -0.19655747, 71: -0.15645898, 72: -3.49380556, 73: -3.5317097, 74: -4.57108006, 75: -4.63425205, 76: -2.88247063, 77: -1.45679675, 78: -0.50290184, 79: -0.18521704, 80: -0.01123956, 81: -0.17483649, 82: -0.63132037, 83: -1.3248562, 89: -0.24135757, 90: -1.04601971, 91: -2.04574044, 92: -3.84544799, 93: -7.28626119, 94: -7.3136314}
    # }
    - {
      name: PBE, # (str) custom name
      # (null, Dict[int, float])
      atomic_energy: {1: -13.587222780835477, 6: -1029.4889999855063, 7: -1484.9814568572233, 8: -2041.9816003861047} 
    }

  node_embedding: 
    type: linear    # [linear, nonlinear, surrounding, group], linear is safer

  edge_embedding: 
    type: identity  # [identity, linear, nonlinear, element, group], identity is safer

  Lmax: 2 # Truncation for node, 2 is recommended.
  lmax: 3 # Truncation for edge, 3 is recommended.
  num_layers: 2 # 2 for correlation >=3, can be higher when correlation=2
  num_channel: 64 # (int), 48~64, 64's accuracy is enough to achieve SOTA, never use channel > 64
  
  radial_basis:
    radial_basis: j0   # [j0, jn, gaussian]
    num_radial_basis: 8 # (int) 8-10 for j0 and jn, 8-64 for gaussian 
    distance_transform: null # [null, Agnesi, Soft], this plug-in from mace, if you do not know what it means, never use
    cutoff_fn: c2poly # [c2poly, c3poly, mollifier, cosine]
    polynomial_cutoff: 5 # (int)
    gaussian_width: 2.0
    order: 0 # (int), specify order for jn, for j0, it is negligible, for jn
    trainable: false # (bool)
    apply_cutoff: true # # (bool) true: cutoff was use in before radial_mlp, false: after radial_mlp
    hidden: [64, 64, 64, 1024] # list(int)
    bias: false # (bool)

  atomic_basis:
    type: spectral # [spectral]
    l1l2: null # [null, <=], restriction for each layer
    ictp_ictc_like: true # always true (cueq not support true, need modify source code)
    conv_weights: [r_ij] # subset of [r_ij, z_ij], at least [r_ij]
    norm: avg_num_neighbors  # [avg_num_neighbors, density] density are from mace
    nonlinear: null # [null, sigmoid_gate, sigmoid_norm, silu_grid]
    resnet: BB # [AB, BB, BAB] A = atomic_basis, B = product_basis, control how resnet connect, BAB are not safe, maybe delete in futrue version
    has_linear_after_nonlinear: true

  product_basis:
    type: spectral # [spectral, spatial, identity]
    l1l2: null  # [null, <=]
    ictp_ictc_like: true
    correlation: 3 # (int) 3 is recommended for 2 layer, 2 is  is recommended for > 2 layer
    num_channel: ${model.config.num_channel}
    # below only useful for spatial product basis
    num_latitude: null
    num_longitude: null
    truncation: ${model.config.lmax}
    trainable_scale: false 

  
  readout_emlp:
    bias: false
    hidden: [16]
    use_alllayer: true # (bool) recommended true, if true, evergy layer has readout, else, only last layer has
    
  scale_shift:
    scale_type: rms_forces # [null, rms_forces, rms_forcesrms_forces_by_element]
    shift_type: null # [null, rms_forces, rms_forcesrms_forces_by_element]
    scale_trainable: false # (bool) 
    shift_trainable: false # (bool) 

  short_range:
    zbl: # metal units, for molecular dynamics, true is recommended
      enable: false
      trainable: false # recommended always false

  long_range:
    les: # for introduction to the arguments, see the official repo: https://github.com/ChengUCB/les
      enable: false
      les_arguments:
        n_layers: 3
        n_hidden: [32, 16]
        add_linear_nn: true
        output_scaling_factor: 0.1
        sigma: 1.0
        dl: 2.0
        remove_self_interaction: true
        remove_mean: true
        epsilon_factor: 1.0
        use_atomwise: false
        compute_bec: false
        bec_output_index: null

  universal_embedding: 
    charges:
      enable: false

    total_charge:
      enable: false

    spin_multiplicity:
      enable: false
      num_embeddings: 3 # (int) 

    electric_field:
      enable: false
      normalizer: 1.0 # (float)

    magnetic_field:
      enable: false
      normalizer: 1.0 # (float)

    initial_noncollinear_magmoms:
      enable: false
      normalizer: 1.0 # (float)

  special: # this field can be thoroughly ignored if you only interested in E/F/S training
  
    charges:
      method: lagrangian # [lagrangian, uniform_distribution]

    hessians:
      num_samples: 2 # traing E/F/Hessian, for each graph, <= num_samples atoms's hessians will be used to train
